server:
  port: 8888

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  application:
    name: message-resource-server

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9000
